# Generated by Django 4.0.2 on 2022-05-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, choices=[('partial_refund', 'Partial Refund'), ('proposal', 'Proposal'), ('pending', 'Pending'), ('invoice', 'Invoice'), ('charge', 'Charge'), ('refund', 'Refund'), ('subscription', 'Subscription'), ('quote', 'Quote')], max_length=15)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('charge_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('stripe_charge_identifier', models.CharField(blank=True, max_length=200)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('stripe_refund_identifier', models.CharField(blank=True, max_length=200)),
                ('last_modified_date_time', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
