# Generated by Django 4.0.2 on 2022-05-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('billing_scheme', models.CharField(blank=True, choices=[('per_unit', 'Per Unit'), ('tiered', 'Tiered')], default='per_unit', max_length=30, null=True)),
                ('currency', models.CharField(choices=[('usd', 'United States Dollar ($)')], default='usd', max_length=30)),
                ('stripe_price_identifier', models.CharField(blank=True, max_length=27, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('stripe_product_identifier', models.CharField(blank=True, max_length=107)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date_time', models.DateTimeField(auto_now=True)),
                ('category', models.JSONField(blank=True, default=dict)),
                ('size', models.CharField(blank=True, choices=[('xxxs', 'XXX-Small'), ('xxs', 'XX-Small'), ('xs', 'X-Small'), ('s', 'Small'), ('m', 'Medium'), ('lg', 'Large'), ('xlg', 'X-Large'), ('xxlg', 'XX-Large'), ('xxxlg', 'XXX-Large')], max_length=200)),
                ('upc', models.IntegerField(blank=True, null=True)),
                ('unit_of_measurement_length', models.CharField(blank=True, choices=[('millimeters', 'Millimeters'), ('centimeters', 'Centimeters'), ('inches', 'Inches'), ('feet', 'Feet'), ('meters', 'Meters'), ('yards', 'Yards')], max_length=200)),
                ('package_length', models.CharField(blank=True, max_length=200, null=True)),
                ('package_width', models.CharField(blank=True, max_length=200, null=True)),
                ('package_depth', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_of_measurement_mass', models.CharField(blank=True, choices=[('milligrams', 'Milligrams'), ('grams', 'Grams'), ('ounces', 'Ounces'), ('pounds', 'Pounds')], max_length=200)),
                ('package_weight', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku', 'name'], name='products_pr_sku_e33d0c_idx'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
